test: Add logout tests
supertokens/backend-sdk-testing pull request #37
Opened 2024-08-21 12:29 UTC by anku255

2024-08-21 12:30 UTC, anku255 commented on test/oauth2provider/oauth2provider.api.test.js
> +    describe("Login", () => {
Moved all the login tests into a separate describe block. Didn't do any changes to the login tests other than fixing the code to create state.

2024-08-21 12:31 UTC, anku255 commented on test/oauth2provider/oauth2provider.api.test.js
> +                state = Buffer.from("some-random-string").toString("base64");
The current code wasn't encoding to base64 correctly.

2024-08-21 12:32 UTC, anku255 commented on test/oauth2provider/oauth2provider.api.test.js
> +    describe("Login", () => {
Perhaps it would be easier for you review, if you just reviewed the "Logout" describe block.

2024-08-21 18:35 UTC, porcellus requested changes

2024-08-21 18:35 UTC, porcellus commented on test/oauth2provider/oauth2provider.api.test.js
> +            const state = Buffer.from("some-random-string").toString("base64");
Please extract these into a `beforeEach` where possible

2024-08-23 08:18 UTC, anku255 commented on test/oauth2provider/oauth2provider.api.test.js
> +            const state = Buffer.from("some-random-string").toString("base64");
done

2024-08-25 22:15 UTC, porcellus approved these changes

2024-08-25 22:15 UTC, merged